"""Add search_config_rpa to lsd_configs

Revision ID: 030d71c1b5d6
Revises: 607dc72d8963
Create Date: 2025-09-20 23:57:29.347741

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '030d71c1b5d6'
down_revision = '607dc72d8963'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lsd_configs', sa.Column('search_config_rpa', sa.JSON(), nullable=True))
    op.alter_column('lsd_stocks', 'match_score',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               type_=sa.Numeric(precision=5, scale=3),
               existing_nullable=True)
    op.drop_index(op.f('idx_lsd_stocks_fprice'), table_name='lsd_stocks')
    op.drop_index(op.f('idx_lsd_stocks_fprice_lsd'), table_name='lsd_stocks')
    op.drop_index(op.f('idx_lsd_stocks_lsd_config_id'), table_name='lsd_stocks')
    op.drop_index(op.f('idx_lsd_stocks_normalized_name'), table_name='lsd_stocks')
    op.drop_index(op.f('idx_lsd_stocks_order_item_id'), table_name='lsd_stocks')
    op.create_index(op.f('ix_lsd_stocks_id'), 'lsd_stocks', ['id'], unique=False)
    op.drop_constraint(op.f('lsd_stocks_order_item_id_fkey'), 'lsd_stocks', type_='foreignkey')
    op.create_foreign_key(None, 'lsd_stocks', 'order_items', ['order_item_id'], ['id'])
    op.drop_index(op.f('idx_order_basket_items_available_stock_id'), table_name='order_basket_items')
    op.drop_index(op.f('idx_order_basket_items_order_basket_id'), table_name='order_basket_items')
    op.create_index(op.f('ix_order_basket_items_id'), 'order_basket_items', ['id'], unique=False)
    op.drop_constraint(op.f('order_basket_items_order_basket_id_fkey'), 'order_basket_items', type_='foreignkey')
    op.create_foreign_key(None, 'order_basket_items', 'order_baskets', ['order_basket_id'], ['id'])
    op.alter_column('order_baskets', 'applied_promocodes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('order_baskets', 'optimization_score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=5, scale=3),
               existing_nullable=True)
    op.drop_index(op.f('idx_order_baskets_optimization_score'), table_name='order_baskets')
    op.drop_index(op.f('idx_order_baskets_order_lsd'), table_name='order_baskets')
    op.drop_index(op.f('idx_order_baskets_status'), table_name='order_baskets')
    op.create_index(op.f('ix_order_baskets_id'), 'order_baskets', ['id'], unique=False)
    op.drop_constraint(op.f('order_baskets_order_id_fkey'), 'order_baskets', type_='foreignkey')
    op.create_foreign_key(None, 'order_baskets', 'orders', ['order_id'], ['id'])
    op.drop_index(op.f('idx_order_items_normalized_name'), table_name='order_items')
    op.drop_index(op.f('idx_order_items_order_id'), table_name='order_items')
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    op.drop_constraint(op.f('order_items_order_id_fkey'), 'order_items', type_='foreignkey')
    op.create_foreign_key(None, 'order_items', 'orders', ['order_id'], ['id'])
    op.alter_column('orders', 'error_details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('idx_orders_status_created'), table_name='orders')
    op.drop_index(op.f('idx_orders_user_status'), table_name='orders')
    op.alter_column('promocode_verifications', 'verification_details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('idx_promocode_verifications_order_basket_id'), table_name='promocode_verifications')
    op.drop_index(op.f('idx_promocode_verifications_problematic'), table_name='promocode_verifications', postgresql_where='(marked_problematic = true)')
    op.drop_index(op.f('idx_promocode_verifications_status'), table_name='promocode_verifications')
    op.create_index(op.f('ix_promocode_verifications_id'), 'promocode_verifications', ['id'], unique=False)
    op.drop_constraint(op.f('promocode_verifications_order_basket_id_fkey'), 'promocode_verifications', type_='foreignkey')
    op.create_foreign_key(None, 'promocode_verifications', 'order_baskets', ['order_basket_id'], ['id'])
    op.alter_column('user_sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'promocode_verifications', type_='foreignkey')
    op.create_foreign_key(op.f('promocode_verifications_order_basket_id_fkey'), 'promocode_verifications', 'order_baskets', ['order_basket_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_promocode_verifications_id'), table_name='promocode_verifications')
    op.create_index(op.f('idx_promocode_verifications_status'), 'promocode_verifications', ['verification_status'], unique=False)
    op.create_index(op.f('idx_promocode_verifications_problematic'), 'promocode_verifications', ['marked_problematic'], unique=False, postgresql_where='(marked_problematic = true)')
    op.create_index(op.f('idx_promocode_verifications_order_basket_id'), 'promocode_verifications', ['order_basket_id'], unique=False)
    op.alter_column('promocode_verifications', 'verification_details',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_index(op.f('idx_orders_user_status'), 'orders', ['user_id', 'status'], unique=False)
    op.create_index(op.f('idx_orders_status_created'), 'orders', ['status', 'created_at'], unique=False)
    op.alter_column('orders', 'error_details',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.create_foreign_key(op.f('order_items_order_id_fkey'), 'order_items', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.create_index(op.f('idx_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('idx_order_items_normalized_name'), 'order_items', ['normalized_name'], unique=False)
    op.drop_constraint(None, 'order_baskets', type_='foreignkey')
    op.create_foreign_key(op.f('order_baskets_order_id_fkey'), 'order_baskets', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_order_baskets_id'), table_name='order_baskets')
    op.create_index(op.f('idx_order_baskets_status'), 'order_baskets', ['status'], unique=False)
    op.create_index(op.f('idx_order_baskets_order_lsd'), 'order_baskets', ['order_id', 'lsd_config_id'], unique=True)
    op.create_index(op.f('idx_order_baskets_optimization_score'), 'order_baskets', [sa.literal_column('optimization_score DESC')], unique=False)
    op.alter_column('order_baskets', 'optimization_score',
               existing_type=sa.Numeric(precision=5, scale=3),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('order_baskets', 'applied_promocodes',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_constraint(None, 'order_basket_items', type_='foreignkey')
    op.create_foreign_key(op.f('order_basket_items_order_basket_id_fkey'), 'order_basket_items', 'order_baskets', ['order_basket_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_order_basket_items_id'), table_name='order_basket_items')
    op.create_index(op.f('idx_order_basket_items_order_basket_id'), 'order_basket_items', ['order_basket_id'], unique=False)
    op.create_index(op.f('idx_order_basket_items_available_stock_id'), 'order_basket_items', ['lsd_stock_id'], unique=False)
    op.drop_constraint(None, 'lsd_stocks', type_='foreignkey')
    op.create_foreign_key(op.f('lsd_stocks_order_item_id_fkey'), 'lsd_stocks', 'order_items', ['order_item_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_lsd_stocks_id'), table_name='lsd_stocks')
    op.create_index(op.f('idx_lsd_stocks_order_item_id'), 'lsd_stocks', ['order_item_id'], unique=False)
    op.create_index(op.f('idx_lsd_stocks_normalized_name'), 'lsd_stocks', ['order_item_id', sa.literal_column('match_score DESC')], unique=False)
    op.create_index(op.f('idx_lsd_stocks_lsd_config_id'), 'lsd_stocks', ['lsd_config_id'], unique=False)
    op.create_index(op.f('idx_lsd_stocks_fprice_lsd'), 'lsd_stocks', ['lsd_config_id', 'fprice'], unique=False)
    op.create_index(op.f('idx_lsd_stocks_fprice'), 'lsd_stocks', ['fprice'], unique=False)
    op.alter_column('lsd_stocks', 'match_score',
               existing_type=sa.Numeric(precision=5, scale=3),
               type_=sa.NUMERIC(precision=3, scale=2),
               existing_nullable=True)
    op.drop_column('lsd_configs', 'search_config_rpa')
    # ### end Alembic commands ###
