"""Add user_sessions table for storing cookies

Revision ID: d06e899ee5d0
Revises: f66951acb50f
Create Date: 2025-09-19 00:48:15.931197

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd06e899ee5d0'
down_revision = 'f66951acb50f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('basket_analyses', 'updated_at')
    op.drop_column('lsd_accounts', 'updated_at')
    op.drop_column('product_prices', 'updated_at')
    op.drop_column('promotions', 'updated_at')
    op.drop_index(op.f('idx_user_sessions_lsd_account_id'), table_name='user_sessions')
    op.drop_column('user_sessions', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_sessions', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_user_sessions_lsd_account_id'), 'user_sessions', ['lsd_account_id'], unique=False)
    op.add_column('promotions', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('product_prices', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('lsd_accounts', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('basket_analyses', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
