"""Add order_id to lsd_stocks

Revision ID: f05448bfddb0
Revises: d8a9c09c4c0e
Create Date: 2025-09-25 09:52:50.585927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f05448bfddb0'
down_revision = 'd8a9c09c4c0e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Шаг 1: Добавляем order_id как nullable
    op.add_column('lsd_stocks', sa.Column('order_id', sa.Integer(), nullable=True))
    
    # Шаг 2: Заполняем order_id из order_items
    op.execute("""
        UPDATE lsd_stocks 
        SET order_id = order_items.order_id
        FROM order_items
        WHERE lsd_stocks.order_item_id = order_items.id
    """)
    
    # Шаг 3: Делаем order_id NOT NULL
    op.alter_column('lsd_stocks', 'order_id', nullable=False)
    
    # Шаг 4: Создаём индекс и foreign key
    op.create_index(op.f('ix_lsd_stocks_order_id'), 'lsd_stocks', ['order_id'], unique=False)
    op.create_foreign_key(None, 'lsd_stocks', 'orders', ['order_id'], ['id'])
    
    # Остальные изменения
    # op.alter_column('lsd_stocks', 'base_unit',  # Комментируем - используется в view
    #            existing_type=sa.VARCHAR(length=10),
    #            type_=sa.String(length=20),
    #            nullable=False)
    
    # Удаляем ненужные колонки (если они есть)
    # op.drop_column('lsd_stocks', 'min_order_amount')  # Комментируем - такой колонки нет в модели
    
    op.alter_column('user_sessions', 'default_delivery_address',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    # op.drop_column('user_sessions', 'sms_code')  # Комментируем - колонка в User, не в UserSession
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_sessions', sa.Column('sms_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.alter_column('user_sessions', 'default_delivery_address',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.add_column('lsd_stocks', sa.Column('min_order_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'lsd_stocks', type_='foreignkey')
    op.drop_index(op.f('ix_lsd_stocks_order_id'), table_name='lsd_stocks')
    op.alter_column('lsd_stocks', 'base_unit',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               nullable=True)
    op.drop_column('lsd_stocks', 'order_id')
    # ### end Alembic commands ###
