"""Change user_sessions to reference lsd_configs directly

Revision ID: 9ea450069b2e
Revises: d06e899ee5d0
Create Date: 2025-09-19 00:57:22.184377

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9ea450069b2e'
down_revision = 'd06e899ee5d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_sessions', sa.Column('lsd_config_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('fk_user_sessions_lsd_account_id'), 'user_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'user_sessions', 'lsd_configs', ['lsd_config_id'], ['id'])
    op.drop_column('user_sessions', 'lsd_account_id')
    op.drop_column('user_sessions', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_sessions', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('user_sessions', sa.Column('lsd_account_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_user_sessions_lsd_account_id'), 'user_sessions', 'lsd_accounts', ['lsd_account_id'], ['id'])
    op.drop_column('user_sessions', 'lsd_config_id')
    # ### end Alembic commands ###
