"""Add order_item_ids_quantity and order_item_ids_cost to lsd_stocks

Revision ID: f25d7aa8bc7a
Revises: 44b3acf35bf4
Create Date: 2025-09-28 16:52:53.286672

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f25d7aa8bc7a'
down_revision = '44b3acf35bf4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('basket_combinations')
    op.drop_index(op.f('idx_valid_baskets_basket_id'), table_name='valid_baskets')
    op.drop_index(op.f('idx_valid_baskets_loss'), table_name='valid_baskets')
    op.drop_index(op.f('idx_valid_baskets_order_id'), table_name='valid_baskets')
    op.drop_table('valid_baskets')
    op.alter_column('lsd_stocks', 'base_unit',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               nullable=False)
    op.alter_column('lsd_stocks', 'delivery_cost',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lsd_stocks', 'delivery_cost',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('lsd_stocks', 'base_unit',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               nullable=True)
    op.create_table('valid_baskets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('basket_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('item_id_1', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_1', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('lsd_1', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('lsd_config_1', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pieces_1', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('base_qty_1', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True),
    sa.Column('price_1', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('loss_1', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('item_id_2', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_2', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('lsd_2', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('lsd_config_2', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pieces_2', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('base_qty_2', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True),
    sa.Column('price_2', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('loss_2', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('item_id_3', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_3', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('lsd_3', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('lsd_config_3', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pieces_3', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('base_qty_3', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True),
    sa.Column('price_3', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('loss_3', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('item_id_4', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_4', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('lsd_4', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('lsd_config_4', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pieces_4', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('base_qty_4', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True),
    sa.Column('price_4', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('loss_4', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('total_goods_cost', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('total_loss', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('delivery_costs', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('total_delivery_cost', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('total_cost', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('total_loss_and_delivery', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('valid_baskets_order_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('valid_baskets_pkey')),
    comment='Валидные корзины после фильтрации для отладки'
    )
    op.create_index(op.f('idx_valid_baskets_order_id'), 'valid_baskets', ['order_id'], unique=False)
    op.create_index(op.f('idx_valid_baskets_loss'), 'valid_baskets', ['total_loss'], unique=False)
    op.create_index(op.f('idx_valid_baskets_basket_id'), 'valid_baskets', ['basket_id'], unique=False)
    op.create_table('basket_combinations',
    sa.Column('basket_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('order_item_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_name', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('lsd_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('found_unit', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('found_quantity', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True),
    sa.Column('base_unit', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('base_quantity', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('fprice', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('fprice_min', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('fprice_diff', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('loss', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('product_url', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('search_query', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('found_name', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('match_score', sa.NUMERIC(precision=5, scale=3), autoincrement=False, nullable=True),
    sa.Column('requested_quantity', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True),
    sa.Column('over_requested_quantity', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('over_order_percent', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('requested_unit', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('order_quantity_in_items', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('min_order_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('lsd_config_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('delivery_cost_model', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
