"""Remove item_url field from lsd_stocks

Revision ID: d8a9c09c4c0e
Revises: a1bac020d692
Create Date: 2025-09-21 20:29:48.889854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8a9c09c4c0e'
down_revision = 'a1bac020d692'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
