"""change_integer_to_biginteger_for_all_ids

Revision ID: 699baa829acc
Revises: 2225d5823b8a
Create Date: 2025-10-10 20:19:31.490845

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '699baa829acc'
down_revision = '2225d5823b8a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop views that depend on tables we're altering
    op.execute('DROP VIEW IF EXISTS optimized_baskets CASCADE')
    op.execute('DROP VIEW IF EXISTS fprice_optimizer CASCADE')
    op.execute('DROP VIEW IF EXISTS fprice_lsd_order CASCADE')
    
    op.create_table('lsd_accounts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('lsd_config_id', sa.BigInteger(), nullable=False),
    sa.Column('auth_data', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_auth_check', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['lsd_config_id'], ['lsd_configs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lsd_accounts_id'), 'lsd_accounts', ['id'], unique=False)
    op.create_table('order_baskets',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('lsd_config_id', sa.BigInteger(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('delivery_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('min_order_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_before_promo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('promocode_discount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_after_promo', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('applied_promocodes', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('promo_verification_status', sa.String(length=50), nullable=True),
    sa.Column('delivery_address', sa.Text(), nullable=True),
    sa.Column('delivery_time_slot', sa.String(length=100), nullable=True),
    sa.Column('cart_url', sa.String(length=1000), nullable=True),
    sa.Column('order_id_in_lsd', sa.String(length=100), nullable=True),
    sa.Column('optimization_score', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('savings_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['lsd_config_id'], ['lsd_configs.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_baskets_id'), 'order_baskets', ['id'], unique=False)
    op.create_table('promocode_verifications',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('order_basket_id', sa.BigInteger(), nullable=False),
    sa.Column('promotion_id', sa.BigInteger(), nullable=True),
    sa.Column('promocode', sa.String(length=100), nullable=False),
    sa.Column('expected_discount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('actual_discount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_difference_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('marked_problematic', sa.Boolean(), nullable=True),
    sa.Column('verification_details', sa.JSON(), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['order_basket_id'], ['order_baskets.id'], ),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promocode_verifications_id'), 'promocode_verifications', ['id'], unique=False)
    op.create_table('order_basket_items',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('order_basket_id', sa.BigInteger(), nullable=False),
    sa.Column('lsd_stock_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity_to_order', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_priority', sa.Boolean(), nullable=True),
    sa.Column('substitution_reason', sa.Text(), nullable=True),
    sa.Column('added_to_lsd_cart', sa.Boolean(), nullable=True),
    sa.Column('add_to_cart_error', sa.Text(), nullable=True),
    sa.Column('lsd_cart_item_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['lsd_stock_id'], ['lsd_stocks.id'], ),
    sa.ForeignKeyConstraint(['order_basket_id'], ['order_baskets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_basket_items_id'), 'order_basket_items', ['id'], unique=False)
    op.drop_index(op.f('idx__basket_analyses_basket_id'), table_name='_basket_analyses')
    op.drop_index(op.f('idx__basket_analyses_order_id'), table_name='_basket_analyses')
    op.drop_index(op.f('idx__basket_analyses_rank'), table_name='_basket_analyses')
    op.execute('DROP TABLE IF EXISTS _basket_analyses CASCADE')
    op.drop_index(op.f('idx_basket_combinations_fprice_id'), table_name='basket_combinations')
    op.drop_index(op.f('idx_basket_combinations_lsd_stock'), table_name='basket_combinations')
    op.drop_index(op.f('ix_bc_order_basket'), table_name='basket_combinations')
    op.drop_index(op.f('ix_bc_order_basket_optimized'), table_name='basket_combinations', postgresql_include=['lsd_name', 'product_name', 'price', 'fprice', 'order_item_ids_cost', 'order_item_ids_quantity'])
    op.drop_index(op.f('ix_bc_order_lsd_basket_partial'), table_name='basket_combinations', postgresql_where='((lsd_config_id IS NOT NULL) AND (order_item_ids_cost IS NOT NULL))', postgresql_include=['order_item_ids_cost', 'delivery_cost_model', 'min_order_amount', 'lsd_name'])
    op.execute('DROP TABLE IF EXISTS basket_combinations CASCADE')
    op.drop_index(op.f('idx_basket_delivery_costs_basket_id'), table_name='basket_delivery_costs')
    op.drop_index(op.f('idx_basket_delivery_costs_lsd_config_id'), table_name='basket_delivery_costs')
    op.drop_index(op.f('idx_basket_delivery_costs_order_id'), table_name='basket_delivery_costs')
    op.drop_index(op.f('ix_bdc_basket'), table_name='basket_delivery_costs')
    op.execute('DROP TABLE IF EXISTS basket_delivery_costs CASCADE')
    op.drop_index(op.f('idx__basket_combinations_basket_id'), table_name='_basket_combinations')
    op.drop_index(op.f('idx__basket_combinations_lsd'), table_name='_basket_combinations')
    op.drop_index(op.f('idx__basket_combinations_order_id'), table_name='_basket_combinations')
    op.execute('DROP TABLE IF EXISTS _basket_combinations CASCADE')
    op.drop_index(op.f('idx_valid_baskets_basket_id'), table_name='valid_baskets')
    op.drop_index(op.f('idx_valid_baskets_loss'), table_name='valid_baskets')
    op.drop_index(op.f('idx_valid_baskets_order_id'), table_name='valid_baskets')
    op.execute('DROP TABLE IF EXISTS valid_baskets CASCADE')
    op.drop_index(op.f('idx_lsd_blocks_block_type'), table_name='lsd_blocks')
    op.drop_index(op.f('idx_lsd_blocks_detected_at'), table_name='lsd_blocks')
    op.drop_index(op.f('idx_lsd_blocks_lsd_config_id'), table_name='lsd_blocks')
    op.drop_index(op.f('idx_lsd_blocks_order_id'), table_name='lsd_blocks')
    op.drop_index(op.f('idx_lsd_blocks_user_id'), table_name='lsd_blocks')
    op.execute('DROP TABLE IF EXISTS lsd_blocks CASCADE')
    op.drop_index(op.f('idx__basket_delivery_costs_basket_id'), table_name='_basket_delivery_costs')
    op.drop_index(op.f('idx__basket_delivery_costs_lsd'), table_name='_basket_delivery_costs')
    op.execute('DROP TABLE IF EXISTS _basket_delivery_costs CASCADE')
    op.alter_column('basket_analyses', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('basket_analyses', 'order_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('basket_analyses', 'is_mono_basket',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Флаг моно-корзины (все товары из одного LSD)',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_constraint(op.f('basket_analyses_order_id_basket_id_key'), 'basket_analyses', type_='unique')
    op.drop_index(op.f('idx_basket_analyses_is_mono'), table_name='basket_analyses', postgresql_where='(is_mono_basket = true)')
    op.drop_index(op.f('idx_basket_analyses_order_id'), table_name='basket_analyses')
    op.drop_index(op.f('idx_basket_analyses_order_rank'), table_name='basket_analyses')
    op.drop_index(op.f('idx_basket_analyses_total_loss_and_delivery'), table_name='basket_analyses')
    op.create_index(op.f('ix_basket_analyses_id'), 'basket_analyses', ['id'], unique=False)
    op.alter_column('lsd_configs', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('lsd_stocks', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('lsd_stocks', 'order_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('lsd_stocks', 'order_item_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('lsd_stocks', 'lsd_config_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('lsd_stocks', 'base_unit',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               nullable=False)
    op.alter_column('lsd_stocks', 'delivery_cost',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('order_items', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('order_items', 'order_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('orders', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('orders_id_seq'::regclass)"))
    op.alter_column('orders', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('orders', 'telegram_message_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.drop_index(op.f('idx_orders_optimization_completed'), table_name='orders')
    op.drop_index(op.f('idx_orders_optimization_started'), table_name='orders')
    op.drop_column('orders', 'optimization_completed_at')
    op.drop_column('orders', 'optimization_started_at')
    op.alter_column('product_prices', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('product_prices', 'lsd_config_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('promotions', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('promotions', 'lsd_config_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('user_messages', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user_messages', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('user_messages', 'order_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('user_messages', 'telegram_message_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('user_messages', 'reply_to_telegram_message_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('user_messages', 'is_document',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='True если сообщение содержит документ',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('user_messages', 'filename',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Имя файла документа',
               existing_nullable=True)
    op.alter_column('user_messages', 'file_size',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Размер файла в байтах',
               existing_nullable=True)
    op.alter_column('user_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_user_messages_user_chat_direction'), table_name='user_messages')
    op.create_index(op.f('ix_user_messages_chat_type'), 'user_messages', ['chat_type'], unique=False)
    op.create_index(op.f('ix_user_messages_id'), 'user_messages', ['id'], unique=False)
    op.alter_column('user_sessions', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user_sessions', 'telegram_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('user_sessions', 'lsd_config_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('user_sessions', 'data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='JSONB with cookie file metadata: {"cookie_file": "path/to/file.json", "cookie_count": 14, "last_updated": "ISO8601"}',
               existing_nullable=True)
    op.drop_index(op.f('idx_user_sessions_cookie_file'), table_name='user_sessions', postgresql_where="((data ->> 'cookie_file'::text) IS NOT NULL)")
    op.drop_index(op.f('idx_user_sessions_last_updated'), table_name='user_sessions')
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('users_id_seq'::regclass)"))
    op.alter_column('users', 'telegram_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'telegram_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('users_id_seq'::regclass)"))
    op.create_index(op.f('idx_user_sessions_last_updated'), 'user_sessions', [sa.literal_column("(data ->> 'last_updated'::text)")], unique=False)
    op.create_index(op.f('idx_user_sessions_cookie_file'), 'user_sessions', [sa.literal_column("(data ->> 'cookie_file'::text)")], unique=False, postgresql_where="((data ->> 'cookie_file'::text) IS NOT NULL)")
    op.alter_column('user_sessions', 'data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='JSONB with cookie file metadata: {"cookie_file": "path/to/file.json", "cookie_count": 14, "last_updated": "ISO8601"}',
               existing_nullable=True)
    op.alter_column('user_sessions', 'lsd_config_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('user_sessions', 'telegram_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('user_sessions', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_user_messages_id'), table_name='user_messages')
    op.drop_index(op.f('ix_user_messages_chat_type'), table_name='user_messages')
    op.create_index(op.f('ix_user_messages_user_chat_direction'), 'user_messages', ['user_id', 'chat_id', 'message_direction'], unique=False)
    op.alter_column('user_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_messages', 'file_size',
               existing_type=sa.INTEGER(),
               comment='Размер файла в байтах',
               existing_nullable=True)
    op.alter_column('user_messages', 'filename',
               existing_type=sa.VARCHAR(length=255),
               comment='Имя файла документа',
               existing_nullable=True)
    op.alter_column('user_messages', 'is_document',
               existing_type=sa.BOOLEAN(),
               comment='True если сообщение содержит документ',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('user_messages', 'reply_to_telegram_message_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('user_messages', 'telegram_message_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('user_messages', 'order_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('user_messages', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('user_messages', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('promotions', 'lsd_config_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('promotions', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('product_prices', 'lsd_config_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('product_prices', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.add_column('orders', sa.Column('optimization_started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('optimization_completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_orders_optimization_started'), 'orders', ['optimization_started_at'], unique=False)
    op.create_index(op.f('idx_orders_optimization_completed'), 'orders', ['optimization_completed_at'], unique=False)
    op.alter_column('orders', 'telegram_message_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('orders', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('orders', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('orders_id_seq'::regclass)"))
    op.alter_column('order_items', 'order_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('order_items', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('lsd_stocks', 'delivery_cost',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('lsd_stocks', 'base_unit',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('lsd_stocks', 'lsd_config_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('lsd_stocks', 'order_item_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('lsd_stocks', 'order_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('lsd_stocks', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('lsd_configs', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_basket_analyses_id'), table_name='basket_analyses')
    op.create_index(op.f('idx_basket_analyses_total_loss_and_delivery'), 'basket_analyses', ['total_loss_and_delivery'], unique=False)
    op.create_index(op.f('idx_basket_analyses_order_rank'), 'basket_analyses', ['order_id', 'basket_rank'], unique=False)
    op.create_index(op.f('idx_basket_analyses_order_id'), 'basket_analyses', ['order_id'], unique=False)
    op.create_index(op.f('idx_basket_analyses_is_mono'), 'basket_analyses', ['order_id', 'is_mono_basket'], unique=False, postgresql_where='(is_mono_basket = true)')
    op.create_unique_constraint(op.f('basket_analyses_order_id_basket_id_key'), 'basket_analyses', ['order_id', 'basket_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('basket_analyses', 'is_mono_basket',
               existing_type=sa.BOOLEAN(),
               comment='Флаг моно-корзины (все товары из одного LSD)',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('basket_analyses', 'order_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('basket_analyses', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.create_table('_basket_delivery_costs',
    sa.Column('basket_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('lsd_config_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('delivery_cost', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('topup', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('lsd_total_basket_cost', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('min_order_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    comment='Временная таблица для debug-режима: стоимость доставки по ЛСД для каждой корзины'
    )
    op.create_index(op.f('idx__basket_delivery_costs_lsd'), '_basket_delivery_costs', ['lsd_config_id'], unique=False)
    op.create_index(op.f('idx__basket_delivery_costs_basket_id'), '_basket_delivery_costs', ['basket_id'], unique=False)
    op.create_table('lsd_blocks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lsd_config_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('block_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='Type of block: qrator, cloudflare, captcha, rate_limit, forbidden, other'),
    sa.Column('http_status', sa.INTEGER(), autoincrement=False, nullable=True, comment='HTTP status code received (403, 429, 503, etc.)'),
    sa.Column('block_reason', sa.TEXT(), autoincrement=False, nullable=True, comment='Human-readable description of the block'),
    sa.Column('blocked_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('html_snippet', sa.TEXT(), autoincrement=False, nullable=True, comment='First 1000 characters of the blocked page for debugging'),
    sa.Column('detected_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['lsd_config_id'], ['lsd_configs.id'], name=op.f('lsd_blocks_lsd_config_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('lsd_blocks_order_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('lsd_blocks_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('lsd_blocks_pkey')),
    comment='Tracks when LSD access is blocked by anti-bot systems (Qrator, Cloudflare, etc.)'
    )
    op.create_index(op.f('idx_lsd_blocks_user_id'), 'lsd_blocks', ['user_id'], unique=False)
    op.create_index(op.f('idx_lsd_blocks_order_id'), 'lsd_blocks', ['order_id'], unique=False)
    op.create_index(op.f('idx_lsd_blocks_lsd_config_id'), 'lsd_blocks', ['lsd_config_id'], unique=False)
    op.create_index(op.f('idx_lsd_blocks_detected_at'), 'lsd_blocks', ['detected_at'], unique=False)
    op.create_index(op.f('idx_lsd_blocks_block_type'), 'lsd_blocks', ['block_type'], unique=False)
    op.create_table('valid_baskets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('basket_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('item_id_1', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_1', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('lsd_1', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('lsd_config_1', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pieces_1', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('base_qty_1', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True),
    sa.Column('price_1', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('loss_1', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('item_id_2', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_2', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('lsd_2', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('lsd_config_2', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pieces_2', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('base_qty_2', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True),
    sa.Column('price_2', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('loss_2', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('item_id_3', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_3', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('lsd_3', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('lsd_config_3', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pieces_3', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('base_qty_3', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True),
    sa.Column('price_3', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('loss_3', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('item_id_4', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_4', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('lsd_4', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('lsd_config_4', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pieces_4', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('base_qty_4', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True),
    sa.Column('price_4', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('loss_4', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('total_goods_cost', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('total_loss', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('valid_baskets_order_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('valid_baskets_pkey')),
    comment='Валидные корзины после фильтрации для отладки'
    )
    op.create_index(op.f('idx_valid_baskets_order_id'), 'valid_baskets', ['order_id'], unique=False)
    op.create_index(op.f('idx_valid_baskets_loss'), 'valid_baskets', ['total_loss'], unique=False)
    op.create_index(op.f('idx_valid_baskets_basket_id'), 'valid_baskets', ['basket_id'], unique=False)
    op.create_table('_basket_combinations',
    sa.Column('basket_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order_item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_name', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('lsd_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('base_unit', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('base_quantity', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('fprice', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('fprice_min', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('fprice_diff', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('loss', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('order_item_ids_quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('min_order_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('lsd_config_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('delivery_cost_model', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('order_item_ids_cost', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('fprice_optimizer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    comment='Временная таблица для debug-режима: все комбинации товаров во всех корзинах'
    )
    op.create_index(op.f('idx__basket_combinations_order_id'), '_basket_combinations', ['order_id'], unique=False)
    op.create_index(op.f('idx__basket_combinations_lsd'), '_basket_combinations', ['lsd_config_id'], unique=False)
    op.create_index(op.f('idx__basket_combinations_basket_id'), '_basket_combinations', ['basket_id'], unique=False)
    op.create_table('basket_delivery_costs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('basket_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('lsd_config_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('lsd_total_basket_cost', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('delivery_cost', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('topup', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('min_order_amount', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_basket_delivery_costs_order'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('basket_delivery_costs_pkey')),
    sa.UniqueConstraint('order_id', 'basket_id', 'lsd_config_id', name=op.f('basket_delivery_costs_order_basket_lsd_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_bdc_basket'), 'basket_delivery_costs', ['basket_id'], unique=False)
    op.create_index(op.f('idx_basket_delivery_costs_order_id'), 'basket_delivery_costs', ['order_id'], unique=False)
    op.create_index(op.f('idx_basket_delivery_costs_lsd_config_id'), 'basket_delivery_costs', ['lsd_config_id'], unique=False)
    op.create_index(op.f('idx_basket_delivery_costs_basket_id'), 'basket_delivery_costs', ['basket_id'], unique=False)
    op.create_table('basket_combinations',
    sa.Column('basket_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('order_item_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_name', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('lsd_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('base_unit', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('base_quantity', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('fprice', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('fprice_min', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('fprice_diff', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('loss', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('order_item_ids_quantity', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('min_order_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('lsd_config_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('delivery_cost_model', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('order_item_ids_cost', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('fprice_optimizer_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='Ссылка на запись в fprice_optimizer - источник данных для этой позиции в корзине'),
    sa.Column('lsd_stock_id', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_index(op.f('ix_bc_order_lsd_basket_partial'), 'basket_combinations', ['order_id', 'lsd_config_id', 'basket_id'], unique=False, postgresql_where='((lsd_config_id IS NOT NULL) AND (order_item_ids_cost IS NOT NULL))', postgresql_include=['order_item_ids_cost', 'delivery_cost_model', 'min_order_amount', 'lsd_name'])
    op.create_index(op.f('ix_bc_order_basket_optimized'), 'basket_combinations', ['order_id', 'basket_id'], unique=False, postgresql_include=['lsd_name', 'product_name', 'price', 'fprice', 'order_item_ids_cost', 'order_item_ids_quantity'])
    op.create_index(op.f('ix_bc_order_basket'), 'basket_combinations', ['order_id', 'basket_id'], unique=False)
    op.create_index(op.f('idx_basket_combinations_lsd_stock'), 'basket_combinations', ['lsd_stock_id'], unique=False)
    op.create_index(op.f('idx_basket_combinations_fprice_id'), 'basket_combinations', ['fprice_optimizer_id'], unique=False)
    op.create_table('_basket_analyses',
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('basket_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_loss', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('total_goods_cost', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('delivery_cost', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('delivery_topup', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('total_delivery_cost', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('total_cost', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('total_loss_and_delivery', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('basket_rank', sa.INTEGER(), autoincrement=False, nullable=True),
    comment='Временная таблица для debug-режима: полный анализ всех корзин с рейтингом'
    )
    op.create_index(op.f('idx__basket_analyses_rank'), '_basket_analyses', ['basket_rank'], unique=False)
    op.create_index(op.f('idx__basket_analyses_order_id'), '_basket_analyses', ['order_id'], unique=False)
    op.create_index(op.f('idx__basket_analyses_basket_id'), '_basket_analyses', ['basket_id'], unique=False)
    op.drop_index(op.f('ix_order_basket_items_id'), table_name='order_basket_items')
    op.drop_table('order_basket_items')
    op.drop_index(op.f('ix_promocode_verifications_id'), table_name='promocode_verifications')
    op.drop_table('promocode_verifications')
    op.drop_index(op.f('ix_order_baskets_id'), table_name='order_baskets')
    op.drop_table('order_baskets')
    op.drop_index(op.f('ix_lsd_accounts_id'), table_name='lsd_accounts')
    op.drop_table('lsd_accounts')
    # ### end Alembic commands ###
