"""add_min_order_and_delivery_to_lsd_stocks

Revision ID: 603157456ae6
Revises: fbcf22b59094
Create Date: 2025-09-26 11:11:49.135180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '603157456ae6'
down_revision = 'fbcf22b59094'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # min_order_amount already exists, only add delivery_cost
    op.add_column('lsd_stocks', sa.Column('delivery_cost', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False))
    # Skipping base_unit type change as it's used by view fprice_lsd_order
    # op.alter_column('lsd_stocks', 'base_unit',
    #            existing_type=sa.VARCHAR(length=10),
    #            type_=sa.String(length=20),
    #            nullable=False)
    op.alter_column('lsd_stocks', 'fprice_calculation',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Текстовое описание формулы расчета fprice',
               existing_nullable=True)
    op.drop_column('user_sessions', 'sms_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_sessions', sa.Column('sms_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.alter_column('lsd_stocks', 'fprice_calculation',
               existing_type=sa.TEXT(),
               comment='Текстовое описание формулы расчета fprice',
               existing_nullable=True)
    # Skipping base_unit type restore as it was not changed
    # op.alter_column('lsd_stocks', 'base_unit',
    #            existing_type=sa.String(length=20),
    #            type_=sa.VARCHAR(length=10),
    #            nullable=True)
    # min_order_amount was already there, only drop delivery_cost
    op.drop_column('lsd_stocks', 'delivery_cost')
    # ### end Alembic commands ###
