"""Remove item_url from lsd_stocks

Revision ID: a1bac020d692
Revises: 105e6377d4af
Create Date: 2025-09-21 20:16:24.024398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1bac020d692'
down_revision = '105e6377d4af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lsd_stocks', 'item_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lsd_stocks', sa.Column('item_url', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
