"""Add item_url to lsd_stocks

Revision ID: 105e6377d4af
Revises: 030d71c1b5d6
Create Date: 2025-09-21 20:11:26.824054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '105e6377d4af'
down_revision = '030d71c1b5d6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lsd_stocks', sa.Column('item_url', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lsd_stocks', 'item_url')
    # ### end Alembic commands ###
